[package]
name = "vent-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vent-runtime = { path = "../vent-runtime"}
vent-common = { path = "../vent-common"}

# egui
egui = "0.22.0"
egui_dock = "0.6.1"

egui-wgpu = "0.22.0"
egui-winit = "0.22.0"

winit = "0.28.6"
wgpu = "0.15.0"
pollster = "0.3.0"

log = "0.4.18"

rfd = "0.11.4"

[target.'cfg(any(not(target_arch = "wasm32"), target_os = "emscripten"))'.dependencies]
env_logger = "0.10.0"
