[package]
name = "vent-assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vent-dev = { path = "../vent-dev" }

wgpu = "0.16.2"
bytemuck = { version = "1.13.1", features = ["derive"] }
log = "0.4"
cfg-if = "1"
crossbeam = "0.8"

# model
tobj = { version = "4.0.0", features = ["async"] }
gltf = "1.2.0"

image = "0.24.7"
