[package]
name = "vent-assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vent-common = { path = "../vent-common"}
wgpu = "0.16.0"
russimp = { version = "2.0.5", features = ["prebuilt"] }
bytemuck = { version = "1.13.1", features = ["derive"] }
glam = "0.24.1"